export const reducerCases={
    SET_TOKEN:"SET_TOKEN",
    SET_PLAYLISTS:"SET_PLAYLISTS",
    SET_USER:"SET_USER",
    SET_PLAYING:"SET_PLAYING",
    SET_PLAYER_STATE:"SET_PLAYER_STATE",
    SET_DARK_MODE:"SET_DARK_MODE",
    SET_REPEAT:"SET_REPEAT",
    SET_SONG_CHANGED:"SET_SONG_CHANGED",
    SET_TRACK_NUMBER:"SET_TRACK_NUMBER",
    SET_SHUFFLE:"SET_SHUFFLE"
}